CREATE TABLE job_history_14 (
EMPLOYEE_ID decimal(6,0) NOT NULL PRIMARY KEY,
START_DATE date NOT NULL, 
END_DATE date NOT NULL, 
JOB_ID varchar (10) NOT NULL, 
DEPARTMENT_ID decimal(4,0) DEFAULT NULL, 
FOREIGN KEY (JOB_ID)
REFERENCES jobs(JOB_ID)
) Engine=InnoDB;





